cabal-version: 3.14
version: 0
build-type: Simple
name: leoconforti-us
author: Leo Conforti
maintainer: leo@leoconforti.us

executable site
  main-is: site.hs
  build-depends:
    base ==4.*,
    blaze-html,
    blaze-markup,
    bytestring,
    clay,
    containers,
    directory,
    exceptions,
    filepath,
    hakyll ==4.16.*,
    hakyll-images,
    haskeline,
    mtl,
    pandoc,
    skylighting,
    text,
    time,
    transformers,
    yaml

-- executable clay-css
--   main-is:          css/clay.hs
--   build-depends:    base == 4.*
--                   , clay
--                   , text
--   default-language: Haskell2010
